---
title: "hw3solutions"
author: "Krishna"
date: "October 30, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r helper}
# install.packages(c("DOS2", "optmatch", "Ritools", "plyr", "rcbalance"))
# install.packages("caret")
library(DOS2)
library(optmatch)
library(RItools)
library(plyr)
library(rcbalance)
library(ggplot2)
library(sensitivitymult)
library(caret)
library(epitools)

################################################
##              helper functions              ##
################################################

# function to summarize matches 
summarize.match <- function(dat, ms, ps.name="prop") {
    adat <- dat
    adat$pair <- ms
    adat <- adat[!is.na(adat$pair),]
    adat.treat <- adat[adat$z==1, ]
    adat.ctrl <- adat[adat$z==0, ]

    adat.m <- merge(adat.treat, adat.ctrl, by="pair", suffixes=c(".1", ".0"))
    adat.m <- adat.m[, -which(names(adat.m) %in% c("z.1", "z.0", "pair"))]
    adat.m <- adat.m[, sort(names(adat.m), index.return=TRUE)$ix]
    
    p0.name <- paste0(ps.name,".", 0)
    p1.name <- paste0(ps.name,".",1)

    # adat.m.tmp.1 <- adat.m[, -which(names(adat.m) %in% c(p0.name, p1.name))]
    # adat.m.tmp.2 <- adat.m[, c(p0.name, p1.name)]

    # adat.m <- cbind(adat.m.tmp.1, adat.m.tmp.2)
    
    return(adat.m)
}


ms.transform <- function(dat.arg, ms.rcbal) {
    ctrl <- seq(sum(dat.arg$z==0))
    matched.ctrl <- ms.rcbal
    unmatched.ctrl <- setdiff(ctrl,ms.rcbal)
    
    dat.tmp <- dat.arg
    dat.tmp$foo <- NA
    dat.tmp$foo[dat.tmp$z==1] <- matched.ctrl
    dat.tmp$foo[dat.tmp$z==0][matched.ctrl] <- matched.ctrl

    return(dat.tmp$foo)    
}


## preprocesses the results of pair matching for an analysis
## using `senm'.
cast.senm <- function(dat, ms.arg, two.outcomes=FALSE) {
    ms <- as.vector(ms.arg)

    y <- dat$y[!is.na(ms)]
    mset <- ms[!is.na(ms)]
    z <- dat$z[!is.na(ms)]
    
    dico.names <- unique(mset)
    dico <- seq(length(dico.names))
    names(dico) <- dico.names
    mset <- as.integer(dico[mset])

    if(two.outcomes==FALSE) {
        return(list(y=y, mset=mset, z=z))
    } else {
        y2 <- dat$y2[!is.na(ms)]
        return(list(y=y, y2=y2, mset=mset, z=z))
    }
}

cast.senm.lc <- function(dat, ms.arg, lc, two.outcomes=FALSE) {
    ms <- as.vector(ms.arg)

    y <- dat$y[!is.na(ms) & dat$lc==lc] 
    mset <- ms[!is.na(ms) & dat$lc==lc]
    z <- dat$z[!is.na(ms) & dat$lc==lc]
    
    dico.names <- unique(mset)
    dico <- seq(length(dico.names))
    names(dico) <- dico.names
    mset <- as.integer(dico[mset])

    if(two.outcomes==FALSE) {
        return(list(y=y, mset=mset, z=z))
    } else {
        y2 <- dat$y2[!is.na(ms)]
        return(list(y=y, y2=y2, mset=mset, z=z))
    }
}

  

make_summary_table <- function(df, ms, features){
  summary <- data.frame(matrix(ncol = 6, nrow = length(features)))
c("name", "age", "gender")
colnames(summary) <- c("exposed_mean_pre","controls_mean_pre","std_diff_pre",
                       "exposed_mean_post","controls_mean_post","std_diff_post")
rownames(summary) <- features
  
   dat.treat <- df[df$z==1,features]
   dat.ctrl <- df[df$z==0,features]
   
   adat <- df
    adat$pair <- ms.1
    adat <- adat[!is.na(adat$pair),]
    adat.treat <- adat[adat$z==1,features ]
    adat.ctrl <- adat[adat$z==0, features]
  summary$exposed_mean_pre <- colMeans(dat.treat)
  summary$controls_mean_pre <- colMeans(dat.ctrl)
  
  summary$exposed_mean_post<- colMeans(adat.treat)
  summary$controls_mean_post <- colMeans(adat.ctrl)
  
  balance <- xBalance(z ~  latitude + longitude + vpd  + ppt + strata(ms.1), data=df)

  summary$std_diff_pre <-  balance[1]$results[1:4]
  summary$std_diff_post <-  balance[1]$results[13:16]
  return(summary)
}


odds.lc <- function(df, ms.1, lc, value){
  mdf <- df[!is.na(ms.1),]
  if (lc %in% c(42,52,71)){
    mdf <- mdf[mdf$lc==lc, ]
  }
  
  cm <- confusionMatrix(as.factor(mdf$z), as.factor(mdf$y))$table
  print(cm)
  odds.ratio.everything = oddsratio.wald(cm)
  or = odds.ratio.everything$measure[2,'estimate']
  lower = odds.ratio.everything$measure[2,'lower']
  upper = odds.ratio.everything$measure[2,'upper']
  p = odds.ratio.everything$p.value[2,'fisher.exact']
  n = odds.ratio.everything$data["Total","Total"]
  combined = list("or" = or, "lower" = lower, "upper" = upper, "p" = p, "n" = n)
  if (is.nan(combined$lower)){
    combined$or = NaN
    combined$upper = NaN
  }
  return(combined)
}

```


```{r}
# sensitivity analyses

df <- read.csv("D:/Krishna/projects/lfmc_for_ignitions/data/r/rct_22_apr_2022.csv")
df <- subset(df, !lc %in% c(41,43,81))
colnames(df)[colnames(df) == 'fire'] <- 'y'
treatment = "z_extreme"
df$z <- df[,treatment]

master_matched = list(y=NULL, mset=NULL, z=NULL)

counter = 0
for (slc in  c(42, 52, 71)){
  sdf = subset(df, lc==slc)
  load(sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/matches/matching_22_apr_2022_%s_%s.RData", treatment, lcmap[lcmap$key==slc,"value"]))
  matched = cast.senm(sdf, ms.1)
  master_matched$y = c(master_matched$y,matched$y)
  master_matched$z = c(master_matched$z,matched$z)
  master_matched$mset = c(master_matched$mset,matched$mset+10000*counter)
  
  # counter = counter + 1
  # gammas = seq(1,3,0.01)
  # pvals = gammas
  # 
  # for(i in seq(1, length(gammas))) {
  #   pvals[i] = senm(y=matched$y,
  #   z=matched$z,
  #   mset=matched$mset,
  #   gamma = gammas[i],
  #   inner=0,
  #   trim=Inf)$pval
  # }
  # 
  # sens = data.frame("confounding.ratio"=gammas,"pvalue"=pvals)
  # 
  # plot <- ggplot(data=sens, aes(x=confounding.ratio, y=pvalue, group=1)) +
  #   geom_line(size = 2)+
  #   geom_point(size = 4)+  theme_bw(base_size = 25)+theme(aspect.ratio=1)
  # print(plot)
  # write.csv(sens,sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/pvalues/p_gamma_24_apr_2022_%s.csv",lcmap[lcmap$key==slc,"value"]), row.names = TRUE)
}
gammas = seq(1,3,0.01)
pvals = gammas
  
for(i in seq(1, length(gammas))) {
    pvals[i] = senm(y=master_matched$y,
    z=master_matched$z,
    mset=master_matched$mset,
    gamma = gammas[i],
    inner=0,
    trim=Inf)$pval
}
sens = data.frame("confounding.ratio"=gammas,"pvalue"=pvals)
  # plot <- ggplot(data=sens, aes(x=confounding.ratio, y=pvalue, group=1)) +
  #   geom_line(size = 2)+
  #   geom_point(size = 4)+  theme_bw(base_size = 25)+theme(aspect.ratio=1)
  # print(plot)
write.csv(sens,sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/pvalues/p_gamma_24_apr_2022_all.csv"), row.names = TRUE)
```




```{r}
treatments <- c("z_extreme")
lcmap <- data.frame("key" = c(0, 42, 52, 71), "value" = c("all","forest", "shrub","grass"))

df <- read.csv("D:/Krishna/projects/lfmc_for_ignitions/data/r/rct_22_apr_2022.csv")

df <- subset(df, !lc %in% c(41,43,81))
table(df$lc)
cat(sprintf("Mean fire in df = %f\n",mean(df$fire)))
colnames(df)[colnames(df) == 'fire'] <- 'y'
reload = FALSE
for (treatment in treatments){
  for (slc in  c(42, 52, 71)){
    sdf = subset(df, lc==slc)
    print(dim(sdf))
    sdf$z <- sdf[,treatment]
    if (reload) {
      load(sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/matching_28_feb_2022_%s.RData", treatment))
    } else{
      options("optmatch_max_problem_size" = Inf)
      
      start.time <- Sys.time()
      # mat.1 <- mdist(z ~ longitude + latitude + vpd_4m  + ppt_1y +  agb +      wind    | lc, data = df)
      # mat.2 <- addcaliper(mat.1, z=df$z, p=df$vpd_4m, caliper=0.1)
      # print(Sys.time() - start.time)
      # mat.2 <- addcaliper(mat.1, z=df$z, p=df$prop, caliper=0.1)
      start.time <- Sys.time()
      # ms.1 <- pairmatch(z ~ longitude + latitude + vpd_4m  + ppt_1y +  agb +      wind    | lc, data = df)
      ppty <- glm(z ~ longitude + latitude , family = binomial(), data = sdf)
      ### For more complicated models, create a distance matrix and pass it to fullmatch.
      mhd = match_on(z ~ longitude + latitude + vpd_4m  + ppt_1y +  agb +  wind, data = sdf) + caliper(match_on(ppty), 1)
      ms.1 <- pairmatch(mhd, data = sdf)
      print(summary(ms.1))
      # ms.1 <- pairmatch(mat.1, data=df, controls = 1, remove.unmatchables = FALSE)
      print(Sys.time() - start.time)
      save(ms.1, file=sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/matches/matching_22_apr_2022_%s_%s.RData", treatment, lcmap[lcmap$key==slc,"value"]))
    }
    balance <- xBalance(z ~ longitude + latitude + vpd_4m  + ppt_1y +  agb +  wind +      strata(ms.1), data = sdf)
    plot(balance)
    # print(balance)
  }
}
# dim(df)
```
```{r}
## exporting matched data for plotting in python
for (slc in  c(42, 52, 71)){
  sdf = subset(df, lc==slc)
  load(sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/matches/matching_22_apr_2022_%s_%s.RData", treatment,        lcmap[lcmap$key==slc,"value"]))
  mdf <- sdf[!is.na(ms.1),]
  matched = cast.senm(sdf, ms.1)
  mdf$match <- matched$mset
  # head(mdf)
  write.csv(mdf,sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/matches/matched_22_apr_2022_extreme_%s.csv",
                        lcmap[lcmap$key==slc,"value"]), row.names = TRUE)
}
```

```{r}
# explorting balance data

for (slc in  c(42, 52, 71)){
  sdf = subset(df, lc==slc)
  sdf$z <- sdf[,treatment]
  load(sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/matches/matching_22_apr_2022_%s_%s.RData", treatment,
               lcmap[lcmap$key==slc,"value"]))
  balance <- xBalance(z ~ longitude + latitude + vpd_4m  + ppt_1y +  agb +  wind +      strata(ms.1), data = sdf)
  write.csv(balance,sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/balance/balance_24_apr_2022_%s.csv",
                            lcmap[lcmap$key==slc,"value"]), row.names = TRUE)
}

```

```{r}
# Odds ratio
lcmap <- data.frame("key" = c(0, 42, 52, 71), "value" = c("all","forest", "shrub","grass"))


df <- read.csv("D:/Krishna/projects/lfmc_for_ignitions/data/r/rct_28_feb_2022.csv")
df <- subset(df, !lc %in% c(41,43,81))
colnames(df)[colnames(df) == 'fire'] <- 'y'
# df <- df[is.na(df$agb) == 0, ]

odds.df <- data.frame("or" = rep(0,12), "lower" = rep(0,12),  "upper" = rep(0,12),  "p" = rep(0,12), "land.cover" = rep("a",12), "threshold" = rep("a",12), "n" = rep(0,12))

i = 1

for (thresh in c("extreme")){
  cat(sprintf("LFMC Threshold = %s\n",thresh))
  df$z <- df[,sprintf("z_%s",thresh)]

  # head(df)
  load(sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/matching_28_feb_2022_z_%s.RData",thresh))
  for (lc in lcmap$key){
    combined = odds.lc(df, ms.1, lc, lcmap[lcmap$key==lc,"value"])
    odds.df[i,1:4] = c(combined$or, combined$lower, combined$upper, combined$p)
    odds.df[i,5:6] = c(lcmap[lcmap$key==lc,"value"], thresh)
    odds.df[i,7] = combined$n
    i = i + 1
  }
}

for (thresh in c("extreme")){
    plot <- ggplot(data = odds.df[odds.df$threshold == thresh,],aes(x = land.cover,y = or, color = land.cover), size = 4) + 
    geom_point(size = 3) + 
    geom_errorbar(aes(ymin = lower, ymax = upper), size = 2) + theme_bw(base_size = 18) +
    geom_hline(yintercept=1, linetype="dashed", color = "black", size = 1) + 
    ggtitle(sprintf("LFMC threshold = %s", thresh)) +
    ylim(-1,5) +
      ylab("Odds ratio")
    counter = 1
    for (lc in lcmap$value){
      p = odds.df[odds.df$threshold == thresh & odds.df$land.cover == lc,"p"]
      n = odds.df[odds.df$threshold == thresh & odds.df$land.cover == lc,"n"]
      lower = odds.df[odds.df$threshold == thresh & odds.df$land.cover == lc,"lower"]
      upper = odds.df[odds.df$threshold == thresh & odds.df$land.cover == lc,"upper"]
      plot <- plot + annotate("text", x = lc, y = -0.5, label = sprintf("p = %0.3f", p))
      plot <- plot + annotate("text", x = lc, y = 0, label = sprintf("n = %d", n))
      counter = counter + 1
    }
    print(plot)
}

```


```{r}
thresh = "extreme"
df <- read.csv("D:/Krishna/projects/lfmc_for_ignitions/data/r/rct_28_feb_2022.csv")
df$z <- df[,sprintf("z_%s",thresh)]
colnames(df)[colnames(df) == 'fire'] <- 'y'
df <- subset(df, !lc %in% c(41,43,81))


load(sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/matching_28_feb_2022_z_%s.RData",thresh))
matched = cast.senm(df, ms.1)
# set.seed(194842)
# matched$y <- sample(c(0,1), replace=TRUE, size=length(matched$y))
pval_1 = senm(y=matched$y,
  z=matched$z,
  mset=matched$mset,
  gamma = 1,
  inner=0,
  trim=Inf)$pval

print(pval_1)

```




