---
title: "hw3solutions"
author: "Krishna"
date: "October 30, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r helper}
# install.packages(c("DOS2", "optmatch", "Ritools", "plyr", "rcbalance"))
# install.packages("caret")
library(DOS2)
library(optmatch)
library(RItools)
library(plyr)
library(rcbalance)
library(ggplot2)
library(sensitivitymult)
library(caret)
library(epitools)

################################################
##              helper functions              ##
################################################

# function to summarize matches 
summarize.match <- function(dat, ms, ps.name="prop") {
    adat <- dat
    adat$pair <- ms
    adat <- adat[!is.na(adat$pair),]
    adat.treat <- adat[adat$z==1, ]
    adat.ctrl <- adat[adat$z==0, ]

    adat.m <- merge(adat.treat, adat.ctrl, by="pair", suffixes=c(".1", ".0"))
    adat.m <- adat.m[, -which(names(adat.m) %in% c("z.1", "z.0", "pair"))]
    adat.m <- adat.m[, sort(names(adat.m), index.return=TRUE)$ix]
    
    p0.name <- paste0(ps.name,".", 0)
    p1.name <- paste0(ps.name,".",1)

    # adat.m.tmp.1 <- adat.m[, -which(names(adat.m) %in% c(p0.name, p1.name))]
    # adat.m.tmp.2 <- adat.m[, c(p0.name, p1.name)]

    # adat.m <- cbind(adat.m.tmp.1, adat.m.tmp.2)
    
    return(adat.m)
}


ms.transform <- function(dat.arg, ms.rcbal) {
    ctrl <- seq(sum(dat.arg$z==0))
    matched.ctrl <- ms.rcbal
    unmatched.ctrl <- setdiff(ctrl,ms.rcbal)
    
    dat.tmp <- dat.arg
    dat.tmp$foo <- NA
    dat.tmp$foo[dat.tmp$z==1] <- matched.ctrl
    dat.tmp$foo[dat.tmp$z==0][matched.ctrl] <- matched.ctrl

    return(dat.tmp$foo)    
}


## preprocesses the results of pair matching for an analysis
## using `senm'.
cast.senm <- function(dat, ms.arg, two.outcomes=FALSE) {
    ms <- as.vector(ms.arg)

    y <- dat$y[!is.na(ms)]
    mset <- ms[!is.na(ms)]
    z <- dat$z[!is.na(ms)]
    
    dico.names <- unique(mset)
    dico <- seq(length(dico.names))
    names(dico) <- dico.names
    mset <- as.integer(dico[mset])

    if(two.outcomes==FALSE) {
        return(list(y=y, mset=mset, z=z))
    } else {
        y2 <- dat$y2[!is.na(ms)]
        return(list(y=y, y2=y2, mset=mset, z=z))
    }
}

cast.senm.lc <- function(dat, ms.arg, lc, two.outcomes=FALSE) {
    ms <- as.vector(ms.arg)

    y <- dat$y[!is.na(ms) & dat$lc==lc] 
    mset <- ms[!is.na(ms) & dat$lc==lc]
    z <- dat$z[!is.na(ms) & dat$lc==lc]
    
    dico.names <- unique(mset)
    dico <- seq(length(dico.names))
    names(dico) <- dico.names
    mset <- as.integer(dico[mset])

    if(two.outcomes==FALSE) {
        return(list(y=y, mset=mset, z=z))
    } else {
        y2 <- dat$y2[!is.na(ms)]
        return(list(y=y, y2=y2, mset=mset, z=z))
    }
}

  

make_summary_table <- function(df, ms, features){
  summary <- data.frame(matrix(ncol = 6, nrow = length(features)))
c("name", "age", "gender")
colnames(summary) <- c("exposed_mean_pre","controls_mean_pre","std_diff_pre",
                       "exposed_mean_post","controls_mean_post","std_diff_post")
rownames(summary) <- features
  
   dat.treat <- df[df$z==1,features]
   dat.ctrl <- df[df$z==0,features]
   
   adat <- df
    adat$pair <- ms.1
    adat <- adat[!is.na(adat$pair),]
    adat.treat <- adat[adat$z==1,features ]
    adat.ctrl <- adat[adat$z==0, features]
  summary$exposed_mean_pre <- colMeans(dat.treat)
  summary$controls_mean_pre <- colMeans(dat.ctrl)
  
  summary$exposed_mean_post<- colMeans(adat.treat)
  summary$controls_mean_post <- colMeans(adat.ctrl)
  
  balance <- xBalance(z ~  latitude + longitude + vpd  + ppt + strata(ms.1), data=df)

  summary$std_diff_pre <-  balance[1]$results[1:4]
  summary$std_diff_post <-  balance[1]$results[13:16]
  return(summary)
}


odds.lc <- function(df, ms.1, lc, value){
  mdf <- df[!is.na(ms.1),]
  if (lc %in% c(42,52,71)){
    mdf <- mdf[mdf$lc==lc, ]
  }
  
  cm <- confusionMatrix(as.factor(mdf$z), as.factor(mdf$y))$table
  print(cm)
  odds.ratio.everything = oddsratio.wald(cm)
  or = odds.ratio.everything$measure[2,'estimate']
  lower = odds.ratio.everything$measure[2,'lower']
  upper = odds.ratio.everything$measure[2,'upper']
  p = odds.ratio.everything$p.value[2,'fisher.exact']
  n = odds.ratio.everything$data["Total","Total"]
  combined = list("or" = or, "lower" = lower, "upper" = upper, "p" = p, "n" = n)
  if (is.nan(combined$lower)){
    combined$or = NaN
    combined$upper = NaN
  }
  return(combined)
}



odds.lc <- function(df, ms.1, lfmc.cat, value){
  mdf <- df[!is.na(ms.1),]
  mdf$pair = ms.1[!is.na(ms.1)]
  mdf <- mdf[mdf$lfmc.cat==lfmc.cat, ]

  
  cm <- confusionMatrix(as.factor(mdf$z), as.factor(mdf$y))$table
  print(cm)
  odds.ratio.everything = oddsratio.wald(cm)
  or = odds.ratio.everything$measure[2,'estimate']
  lower = odds.ratio.everything$measure[2,'lower']
  upper = odds.ratio.everything$measure[2,'upper']
  p = odds.ratio.everything$p.value[2,'fisher.exact']
  n = odds.ratio.everything$data["Total","Total"]
  combined = list("or" = or, "lower" = lower, "upper" = upper, "p" = p, "n" = n)
  if (is.nan(combined$lower)){
    combined$or = NaN
    combined$upper = NaN
  }
  return(combined)
}

sensitivity <- function(filepath, savepath_matching, savepath_pvalues) {

  df <- read.csv(filepath)
  df <- subset(df, !lc %in% c(41,43,81))
  colnames(df)[colnames(df) == 'fire'] <- 'y'

  load(savepath_matching)
  
  matched = cast.senm(df, ms)
  gammas = seq(1,2,0.01)
  pvals = gammas
  
  for(i in seq(1, length(gammas))) {
    pvals[i] = senm(y=matched$y,
    z=matched$z,
    mset=matched$mset,
    gamma = gammas[i],
    inner=0,
    trim=Inf)$pval
  }
  
  sens = data.frame("confounding.ratio"=gammas,"pvalue"=pvals)
  write.csv(sens,savepath_pvalues, row.names = TRUE)
  ggplot(data=sens, aes(x=confounding.ratio, y=pvalue, group=1)) +
  geom_line(size = 2)+
  geom_point(size = 4)+  theme_bw(base_size = 25)+theme(aspect.ratio=1)
}

# matching

make.match <- function(filepath, savepath_matching) {
  df <- read.csv(filepath)
  
  df <- subset(df, !lc %in% c(41,43,81))
  colnames(df)[colnames(df) == 'fire'] <- 'y'
  
  mat.1 <- mdist(z ~ longitude + latitude + vpd_4m  + ppt_1y +  agb +      wind      | lc, data = df)
  ms <- pairmatch(mat.1, data=df, controls = 1, remove.unmatchables = FALSE)
  save(ms, file=savepath_matching)
  balance <- xBalance(z ~ longitude + latitude + vpd_4m  + ppt_1y +  agb +  wind +      strata(ms), data = df)
  write.csv(balance, savepath_balance, row.names = TRUE)
  plot(balance)
}

```



```{r}
states = c("Washington", "Oregon","California","Idaho",
          "Utah","Nevada","New Mexico",
          "Wyoming","Montana","Colorado")

options("optmatch_max_problem_size" = Inf)

for (state in states){
  date = "20-04-22"
  filepath = sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/panels/rct_%s_%s.csv", date, state)
  
  savepath_matching = sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/matches/matching_%s_%s.RData", date, state)
  savepath_balance = sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/balance/balance_%s_%s.csv", date, state)
  savepath_pvalues = sprintf("D:/Krishna/projects/lfmc_for_ignitions/data/r/pvalues/p_gamma_%s_%s.csv", date, state)
  
  start.time <- Sys.time()
  make.match(filepath, savepath_matching)
  cat("Time taken for matching for ",state," ",Sys.time() - start.time)
  start.time <- Sys.time()

  sensitivity(filepath, savepath_matching, savepath_pvalues)
  cat("Time taken for calc. sensitivity for ",state," ",Sys.time() - start.time)
}

```
